# Generated by Django 4.2.23 on 2026-06-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="ai_points",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="ai_targets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="SavedSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("cover_url", models.URLField(blank=True)),
                ("summary", models.TextField()),
                ("points", models.JSONField(default=list)),
                ("targets", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
